### ISSUE TITLE
Entity - Comment structure

### ISSUE THREAD

**Issue by Axecibles-Dev** [m4rise/blog#10]
Le champ title a une longueur de 255 caractères mais un assert de maximum 96 est spécifié, qu'elle est la bonne valeur ?
https://github.com/m4rise/blog/blob/8920dca5444370cbc5543cc05782306f34f87dd4/src/Entity/Comment.php#L24-L29

**Comment by m4rise** [comment]
C'est effectivement une coquille, le titre d'un commentaire n'a pas vocation à être très long.
