### ISSUE TITLE
Notification - Utilisation d'un service mail

### ISSUE THREAD

**Issue by Axecibles-Dev** [m4rise/blog#11]
Très bonne idée d'avoir crée une classe gérant l'envoi du mail en dehors du contrôleur, cela permet de le simplifier.

Cependant, votre classe Notification possède une dépendance forte à SwiftMailer pour l'envoi des mails, le jour ou vous changerez de librairie, vous serrez obligé de modifier tout votre code. Pouvez-vous me proposer un correctif utilisant de l'injection de dépendances ?

https://github.com/m4rise/blog/blob/8920dca5444370cbc5543cc05782306f34f87dd4/src/Notifications/ContactNotification.php#L26-L30

**Comment by m4rise** [comment]
Le plus simple serait certainement de créer une interface mailer qui serait injectée dans le constructeur. D'autres classes pourraient l'implémenter, dont l'une adaptant Swift_Mailer. Je travaille sur le correctif.
