### ISSUE TITLE
Lier l'auteur d'un post à la table user

### ISSUE THREAD

**Issue by Axecibles-Dev** [m4rise/blog#14]
Dans un post, le nom de l'auteur est enregistré dans la table post. l doit être en liaison avec le champ nickname de la table user.

**Comment by m4rise** [comment]
Je mets en place une relation entre User et Post.

Je vais rajouter directement l'admin actuellement connecté en tant qu'auteur de l'article lors de la soumission du formulaire.

Une autre alternative pourrait être de proposer un select (EntityType) qui permettrait de choisir parmi la liste d'admins qui en est l'auteur lors de la création/modification d'un post.
